<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>tool_create_account_paykickstart</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.14.1" />
    <PackageReference Include="MiniExcel" Version="1.42.0" />
    <PackageReference Include="Selenium.WebDriver" Version="4.40.0" />
    <PackageReference Include="WebDriverManager" Version="2.17.6" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Windows.Forms.DataVisualization" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Extensions\buster.crx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>